apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: cwansart.de-bar:latest
        imagePullPolicy: Never # required to use local images
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bar-ingress
spec:
  rules:
    - host: bar.cwansart.de
      http:
        paths:
          - backend:
              serviceName: bar-service
              servicePort: 80