apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: cwansart.de-foo:latest
        imagePullPolicy: Never # required to use local images
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foo-ingress
spec:
  rules:
    - host: foo.cwansart.de
      http:
        paths:
          - backend:
              serviceName: foo-service
              servicePort: 80